### ISSUE TITLE
Add capability to visualize a data table

### ISSUE THREAD

**Issue by k8hertweck** [ergonyc/omicser#18]

**Comment by ergonyc** [comment]
Tables are rendered in 1) playground with an "omics" meta-info browser rendered below and 2) in a separate tab where the three core tables are rendered - omic meta, sample meta, and differential expression

TODO:
- [ ] UI refinement
- [ ] scaling options for omics values boxplots
- [ ] javascript to find floating point columns and dynamically render in 2 or 3 sig digits scientific notation
