### ISSUE TITLE
follow up to render website

### ISSUE THREAD

**Issue by k8hertweck** [ergonyc/omicser#26]
After approval of #24 :

- [x] fix labeling of drop-down items in "Articles" section of website (basically, titles of the vignettes)
- [ ] organization of information between main page, getting started, etc

**Comment by ergonyc** [comment]
I re-rendered website and pushed to `docs/` for github.io site.    I think that we should render the website to its own branch.  
Yes or No?

Deadline for decision:  before transfer of repo to NDCN & activation of github actions for automatic update/rendering
