### ISSUE TITLE
Format documentation via pkgdown

### ISSUE THREAD

**Issue by k8hertweck** [ergonyc/omicser#7]
We could use [pkgdown](https://pkgdown.r-lib.org/) to create a website that presents documentation in a way that will be especially appealing to folks who aren't computationally savvy. It would be a nice way to share tutorials/articles/vignettes that we develop for different use cases/datasets/audiences.

**Comment by ergonyc** [comment]
Yes!  I was talking with Vilas today (who is spinning it up and also getting a "minimally" coding proficient and "highly" coding proficient tester from his lab on it).  I didn't really know the R tools for doing it.   I think we should put this on a high to medium priority after the inital "beta" launch.
